Merge `search-v2-infrastructure/terraform/environment` into `terraform/deployments/search-api-v2`
alphagov/govuk-infrastructure pull request #1533
Opened 2024-11-25 15:11 UTC by ianhowell-gds

## What

This is an import of the code in `https://github.com/alphagov/search-v2-infrastructure.git` directory `terraform/environment` into `terraform/deployments/search-api-v2`

## Why

We believe that the separate repo for search-v2-infrastructure is a tech debt as `govuk-infrastructure` is the definitive resource for [GOV.UK](http://gov.uk/) infrastructure as code. We are concerned that the leaving this tech debt carries two risks:
  1. `search-v2-infrastructure` will not be maintained as well as `govuk-infrastructure`
  2. that the longer this debt is left the harder it will be to resolve.

2024-11-25 15:28 UTC, rtrinque approved these changes
Looks good

2024-11-26 11:20 UTC, csutter requested changes
This looks great so far – thanks for taking this off my plate 🙏 

See my comment about the module that also needs migrating, and ideally I'd like to get the following PRs in place on the original repo _before_ we merge this:
* https://github.com/alphagov/search-v2-infrastructure/pull/314 (to save us from migrating about-to-be-decommissioned resources)
* https://github.com/alphagov/search-v2-infrastructure/pull/315 (I'll need this soon and don't want to risk the infra pipeline being broken)

Also just a thought: How much do we consider it worth keeping Git history here? The history is still available in the old repo (which I'm assuming we'll eventually archive), so we can probably just squash this into a single commit – although if you think it's more useful to have it around I'm happy to leave it as is.

2024-11-26 11:20 UTC, csutter commented on terraform/deployments/search-api-v2/discovery_engine.tf
> +  source = "../modules/google_discovery_engine_restapi"
This depends on the [`discovery_engine_restapi` module](https://github.com/alphagov/search-v2-infrastructure/tree/main/terraform/modules/google_discovery_engine_restapi) that will also need migrating at the same time 💡

2024-11-26 11:57 UTC, ianhowell-gds commented
Closing this PR and will recreate it without the decommissioned resources and will include the modules directory

2024-11-26 11:57 UTC, closed without merging