update lifecycle rule for new deployed-to-production tag
alphagov/govuk-infrastructure pull request #739
Opened 2022-09-08 13:29 UTC by desenhar

https://trello.com/c/MK34KlBn/980-lifecycle-rules-for-ecr-to-clean-up-images

2022-10-03 09:01 UTC, theseanything requested changes

2022-10-03 09:01 UTC, theseanything commented on terraform/deployments/ecr/main.tf
> +          "type" : "expire"
Not sure I understand this rule - it reads as if its to expire any image with the tag prefix "deployed-to", rather than retain.

2022-10-03 09:01 UTC, theseanything commented on terraform/deployments/ecr/main.tf
> +        "description" : "Rule 1",
Missing description

2022-10-03 09:01 UTC, theseanything commented on terraform/deployments/ecr/main.tf
> +          "tagPrefixList" : ["v"],
Nit: I don't think we prefix any images tags with "v"?

2022-10-03 09:21 UTC, marcpomfret commented on terraform/deployments/ecr/main.tf
> +        "description" : "Rule 1",
Description should probably be something like 'Keep images tagged as "deployed-to-<env>"'

2022-10-25 11:13 UTC, theseanything commented
Closed in favour of https://github.com/alphagov/govuk-infrastructure/pull/765

2022-10-25 11:13 UTC, closed without merging